backend:
  name: github
  repo: amelv/netlify-cms-react-mdx-test


media_folder: "public/images"
public_folder: "images"

collections:
  - name: 'mdx'
    label: 'Mdx Example'
    description: 'Documentation'
    folder: 'src'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    fields:
        -  {label: "Title", name: "title", widget: "string"}
        -  {label: "Body", name: "body", widget: "markdown"}
  - name: settings
    label: Settings
    files:
      - file: public/manifest.json
        name: manifest
        label: 'Manifest Settings'
        fields:
          - name: short_name
            label: 'Short Name'
            widget: string
            required: true
          - name: name
            label: 'Name'
            widget: string
            required: true
          - name: start_url
            label: 'Start URL'
            widget: string
            default: '.'
            required: true
          - name: display
            label: 'Display Type'
            widget: string
            default: 'standalone'
            required: true
          - name: theme_color
            label: 'Theme Color'
            widget: string
            default: '#000000'
            required: true
          - name: background_color
            label: 'Theme Color'
            widget: string
            default: '#FFFFFF'
            required: true
          - name: icons
            widget: list
            label: 'Icons'
            allow_add: true
            fields:
              - widget: string
                name: src
                label: Source
              - widget: string
                name: sizes
                label: 'Sizes'
              - widget: string
                name: type
                label: 'Mime Type'
